spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

logging:
    level:
        tk.mybatis: DEBUG
        com.liang.lagou: DEBUG